---
# vars for web01 host - apache2

apache2_create_vhost: True
apache2_vhost:
  - name: alcafaz.test
    server_name: www.alcafaz.test
    conf_name: alcafaz.test.conf
    port: 80
    create_index: True
