---

- name: install bind
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - bind9
      - bind9utils
      - bind9-doc

- name: Copy named conf file
  template:
    src: ../files/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: restart named

- name: Copy named conf local file
  template:
    src: ../files/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    backup: yes
    owner: root
    group: bind
    mode: 0640
  notify: restart named

- name: Make zones directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy forward file
  template:
    src: ../files/db.forward.j2
    dest: /etc/bind/zones/db.{{domain}}
    owner: root
    group: bind
    mode: 0640
  with_dict: "{{ records }}"
  notify: restart named

- name: Copy reverse file
  template:
    src: ../files/db.reverse.j2
    dest: /etc/bind/zones/db.{{rev_domain}}
    owner: root
    group: bind
    mode: 0640
  with_dict: "{{ records }}"
  notify: restart named

- name: Open firewall port
  ufw:
    rule: allow
    port: 53