---
# defaults file for apache2
apache2_packages:
  - apache2

apache2_create_vhost: True
apache2_remove_default_vhost: True

apache2_path: /etc/apache2
apache2_default_vhost_name: 000-default.conf
apache2_default_port: '80'
apache2_document_root: /var/www

apache2_vhost:
  # example.com:
  #   server_name: www.example.com
  #   conf_name: example.com.conf
  alcafaz.test:
    conf_name: alcafaz.test.conf
    server_name: alcafaz.test
