---
#
# - debug:
#     msg: "{{playbook_dir}}"

- name: Check OS (bind9)
  fail: msg="Not a Debian based system"
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Update apt cache
  apt:
    update_cache: true
  changed_when: false

- name: Install packages
  apt:
    state: latest
    name:
      - aptitude
      - bind9
      - bind9utils
      - bind9-host

- name: Check if bind9 log folder exists
  stat: path="/var/log/bind"
  register: bind9_dir_log

#- debug:
#    msg: "{{bind9_dir_log}}"

- name: Create bind9 log folder
  file:
    path: /var/log/bind
    owner: bind
    group: bind
    mode: 0640
    state: directory
  when: bind9_dir_log.stat.exists == False

- name: Check if logfile already exists
  stat: path="/var/log/bind/bind.log"
  register: bind9_logfile

- name: Create bind9 logfile
  file:
    path: /var/log/bind/bind.log
    owner: bind
    group: bind
    mode: 0640
    state: '{{ "file" if bind9_logfile.stat.exists else "touch" }}'




#flush_handlers makes Ansible run any handler tasks which have thus far been notified. 
#Ansible inserts these tasks internally at certain points to implicitly trigger handler runs 
#(after pre/post tasks, the final role execution, and the main tasks section of your plays).
- meta: flush_handlers