---
# install and configure bind9

- name: Check OS
  fail:
    msg: "Not a Debian base system!"
  when: ansible_distribution != 'Debian' and ansible_distribution  != 'Ubuntu'

- name: Installation for Debian based systems
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'