---
aux: test_var_log1

user: admin
user_password: qwerty
supersede_dhcp: True
hostname_name: alcafaz.test
hostname_domain_name: alcafaz.test
dhcp_config_ns1: 192.168.100.5
dhcp_config_ns2: 1.1.1.1
packages_to_install:
  - tree
  - git
