---
# tasks file for cyrus-imap

#TODO: utilizar vari치vel default_mail_group
- name: Verificar se o grupo 'mail' existe
  shell: getent group mail | awk -F':' '{print $1}'
  register: group_mail_exists
  ignore_errors: true

- debug: msg="GROUP 'mail' EXISTS"
  when: group_mail_exists.stdout == "mail"

#TODO: utilizar vari치vel default_mail_group
#-r: create a system account
- name: Criar grupo 'mail'
  shell: groupadd -fr mail
  when: group_mail_exists.stdout != "mail"

#TODO: utilizar vari치vel default_cyrus_user
- name: verificar se existe o utilizador cyrus
  shell: getent passwd cyrus | awk -F':' '{print $1}'
  register: cyrus_user_exists
  ignore_errors: true

- debug: msg="USER 'cyrus' EXISTE!!"
  when: cyrus_user_exists.stdout == "cyrus"

#TODO: utilizar vari치vel default_cyrus_user
#The var/lib/imap directory above is an example. Use the same directory specified in the configdirectory option in imapd.conf(5).
- name: Criar utilizador cyrus e adicionar ao grupo mail
  shell: useradd -c "Cyrus IMAP Server" -d /var/lib/cyrus -G mail,{{ default_sasl_group }} -s /bin/bash -r cyrus
  when: cyrus_user_exists.stdout != "cyrus"

- name: Install cyrus-imap packages
  apt:
    name: "{{ cyrus_imap_packages }}"
    update_cache: true
    state: present
  notify:
    - restart cyrus-imap

- name: Copy cyrus.conf conf file
  template:
    src: cyrus.conf.j2
    dest: /etc/cyrus.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart cyrus-imap

- name: Copy imapd.conf conf file
  template:
    src: imapd.conf.j2
    dest: /etc/imapd.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart cyrus-imap

- name: mount dir /run/cyrus
  mount:
    path: /var/spool/postfix/run/cyrus
    src: /run/cyrus
    opts: bind,rw
    state: mounted
    fstype: none

- name: mount dir /run/saslauthd
  mount:
    path: /var/spool/postfix/run/saslauthd
    src: /run/saslauthd
    opts: bind,rw
    state: mounted
    fstype: none

- name: add group mail to postfix user
  user:
    name: postfix
    groups: mail
    append: true

# - name: open port 143 on ufw
#   ufw:
#     rule: allow
#     port: '143'
#     proto: tcp
#   notify: restart ufw
