---

- name: include add/remove host task
  include_tasks: add_remove_host_ip.yml
  tags: never, add_remove_ip

- name: include kvm change vm state task
  include_tasks: kvm_change_vm_state.yml
  tags: never, start, shutdown, pause, unpause
