---
  pre_tasks:
    - name: Update apt cache if needed
      apt: 
        update_cache: true
        cache_valid_time: 3600 # 1 hour

- name: Install apache web server
  apt:
    pkg: "{{ apache_package }}"
    state: present

#ansible-playbook -K playbook.yml -l app
# -l limita a execução do playbook apenas ao grupo 'app'
# -K sudo user

- name: Push future alcafaz.test virtual host configuration
  copy:
    src: ../files/alcafaz.test/alcafaz.test.conf
    dest: /etc/apache2/sites-available/alcafaz.test.conf
    mode: 0640 
    #   User   | Group | Other
    #   r+w    | r     |    

    #chmod 777 
    #    User  | Group | Other
    #   r+w+x  | r+w+x | r+w+x


- name: Push future diogof.test virtualhost configuration
  copy: 
    src: ../files/diogof.test/diogof.test.conf
    dest: /etc/apache2/sites-available/diogof.test.conf

- name: Activates our virtualhost
  command: a2ensite alcafaz.test

- name: Activates diogof.test virtualhost
  command: a2ensite diogof.test

- name: Check that our config is valid
  command: apache2ctl configtest


- name: Deactivates the defautl virtualhost
  command: a2dissite 000-default

- name: Deactivates the defautl ssl virtualhost
  command: a2dissite default-ssl
  notify:
    restart apache

- name: Disable the default virtualhost
  file:
    dest: /etc/apache2/sites-enabled/000-default
    state: absent
  notify:
    - restart apache

- name: Remove app1.conf file
  file:
    dest: /etc/apache2/sites-enabled/app1
    state: absent
  notify:
    - restart apache

- name: Disable the default ssl virtualhost
  file:
    dest: /etc/apache2/sites-enabled/default-ssl
    state: absent
  notify:
    - restart apache

- name: Activates alcafaz.test virtualhost
  file:
    src: /etc/apache2/sites-available/alcafaz.test.conf
    dest: /etc/apache2/sites-enabled/alcafaz.test
    state: link
  notify:
    - restart apache

- name: Activates diogof.test virtualhost
  file:
    src: /etc/apache2/sites-available/diogof.test.conf
    dest: /etc/apache2/sites-enabled/diogof.test
    state: link
  notify:
    - restart apache

- name: Copy alcafaz.test html file
  copy:
    src: ../files/alcafaz.test/index.html
    dest: /var/www/alcafaz.test/

- name: Copy diogof.test html file
  copy:
    src: ../files/diogof.test/index.html
    dest: /var/www/diogof.test/

- name: open ufw port 80
  ufw:
    rule: allow
    port: http
    proto: tcp