---
- hosts: localhost
  gather_facts: False
  become: False

  vars:
    mkdocs_local_path: /home/diogo/Documents/estagio-docs
    mkdocs_build_config: "{{ mkdocs_local_path }}/mkdocs.yml"
    mkdocs_build_output_dir: /tmp/site
    mkdocs_remote_site_path: /var/www/ansible.diogof.pt
    mkdocs_remote_host:
      user: diogo
      domain: diogof.pt
      ssh_port: '2849'
    mkdocs_remote_path: /var/www/ansible.diogof.pt/

  tasks:
    - name: Build mkdocs
      command: mkdocs build -f {{ mkdocs_build_config }} -d {{ mkdocs_build_output_dir }}

    - name: Push mkdocs to remote host
      command: >
          rsync -a
          -e 'ssh -p {{ mkdocs_remote_host.ssh_port }}
          -i /home/diogo/.ssh/id_rsa' {{ mkdocs_build_output_dir }} \
          {{ mkdocs_remote_host.user }}@{{ mkdocs_remote_host.domain }}:{{ mkdocs_remote_path }} \

  post_tasks:
    - debug: msg="OK"



#
# ansible-playbook 05.push-mkdocs-to-remote.yml
