---
- hosts: mailservers
  become: True

  pre_tasks:
    - name: Ensure that debconf is installed
      apt:
        name: debconf
        state: present

  roles:
   - postfix
   - cyrus_sasl2
   - cyrus_imap
   - apache2
   - postgresql
   - mailman3

#
#
# Variáveis definidas no host_vars/group_vars
# Modificar as variáveis de acordo com a configuração do host
#
# ansible-playbook 06.mailman3.yml -i /etc/ansible/inventories/alcafaz.test/hosts
