---
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-cli
  - php-common
  - php-curl
  - php-dom
  - php-exif
  - php-fileinfo
  - php-json
  - php-mbstring
  - php-mysqli
  - php-imagick
  - php-xml
  - php-zip
  - php-gd
  - php-xmlrpc
  - php-soap
  - php-intl
