---
# tasks file for apache2

- name: Verificar OS
  fail:  msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"
  tags: always

- name: Install apache2 packages
  apt: name="{{ apache2_packages }}" state=present
  notify: restart apache2
  tags: apache2, setup

- name: Create configuration file to each virtual host
  template:
    src: vhost.conf.j2
    dest: "{{ apache2_site_available_path }}/{{ item.name }}.conf"
    backup: yes
    owner: root
    group: root
    mode: 0644
  with_items: "{{ apache2_vhost }}"
  when: apache2_create_vhost
  tags: apache2, config

- name: Create directory to each virtual host
  file:
    path: "{{ apache2_document_root }}/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ apache2_vhost }}"
  when: apache2_create_vhost
  tags: apache2, config

- name: Create index.html file to each virtual host
  template:
    src: index_page.html.j2
    dest: "{{ apache2_document_root }}/{{ item.name }}/index.html"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ apache2_vhost }}"
  when: apache2_create_vhost and item.create_index
  tags: apache2, config

- name: Check apache2 config
  command: apache2ctl configtest
  register: apache2_test_config
  changed_when: False
  tags: apache2, config

- name: Debug apache2 config test
  debug: msg="{{ apache2_test_config }}" verbosity=1

- name: Activate each virtual host
  command: a2ensite {{ item.name }}
  notify: restart apache2
  with_items: "{{ apache2_vhost }}"
  register: res_enable_site
  changed_when: "'Enabling site ' ~ item.name ~ '.' in res_enable_site.stdout"
  when: apache2_create_vhost
  tags: apache2, config

- name: Remove default vhost
  file:
    path: "{{ apache2_path }}/sites-enabled/{{ apache2_default_vhost_name }}"
    state: absent
  notify: restart apache2
  when: apache2_remove_default_vhost
  tags: apache2, config

- name: Open port on firewall for http
  ufw:
    rule: 'allow'
    port: "{{ apache2_default_port }}"
    proto: tcp
  tags: apache2, config
