---
# tasks file for postfix

- name: Set postfix option hostname
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ postfix_mailname }}"
    vtype: string

- name: Set postfix option type as internet site
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "{{ postfix_main_mailer_type }}"
    vtype: string

- name: Set postfix option mynetworks
  debconf:
    name: postfix
    question: postfix/mynetworks
    value: "{{ postfix_mynetworks }}"
    vtype: string

- name: Set postfix delimiter option
  debconf:
    name: postfix
    question: postfix/recipient_delim
    value: "{{ postfix_recipient_delim }}"
    vtype: string

- name: Set postfix root root address
  debconf:
    name: postfix
    question: postfix/root_address
    value: "{{ postfix_root_address }}"
    vtype: string

- name: Instalar postfix
  apt:
    name: "{{ postfix_packages }}"
    update_cache: true
    state: present
  notify:
    - restart postfix

- name: Instalar Postfix Policy SPF
  apt:
    name: "{{ postfix_spf_package }}"
    update_cache: true
    state: present
  when: postfix_use_spf
  notify:
    - restart postfix

- name: Create virtual recipient domains file
  template:
    src: files/virtual_recipient_domains.j2
    dest: /etc/postfix/virtual_recipient_domains
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Create virtual recipients file
  template:
    src: files/virtual_recipients.j2
    dest: /etc/postfix/virtual_recipients
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Create postfix main.cf file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Create postfix master.cf file
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Postmap virtual recipients, virtual_recipient_domains
  shell: "{{ item }}"
  with_items:
    - postmap /etc/postfix/virtual_recipient_domains
    - postmap /etc/postfix/virtual_recipients
  notify: restart postfix
