---
# tasks file for postfix

- name: Verificar OS
  fail:  msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"
  tags: always

- name: Set postfix option hostname
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ postfix_mailname }}"
    vtype: string
  tags: postfix, config

- name: Set postfix option type as internet site
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "{{ postfix_main_mailer_type }}"
    vtype: string
  tags: postfix, config

- name: Set postfix option mynetworks
  debconf:
    name: postfix
    question: postfix/mynetworks
    value: "{{ postfix_mynetworks }}"
    vtype: string
  tags: postfix, config

- name: Set postfix delimiter option
  debconf:
    name: postfix
    question: postfix/recipient_delim
    value: "{{ postfix_recipient_delim }}"
    vtype: string
  tags: postfix, config

- name: Set postfix root root address
  debconf:
    name: postfix
    question: postfix/root_address
    value: "{{ postfix_root_address }}"
    vtype: string
  tags: postfix, config

- name: Instalar postfix
  apt: name="{{ postfix_packages }}" state=present
  notify: restart postfix
  tags: postfix, setup

- name: Instalar Postfix Policy SPF
  apt: name="{{ postfix_spf_package }}" state=present
  when: postfix_use_spf
  notify: restart postfix
  tags: postfix, setup

- name: Create virtual recipient domains file
  template:
    src: virtual_recipient_domains.j2
    dest: /etc/postfix/virtual_recipient_domains
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: postfix, config

- name: Create virtual recipients file
  template:
    src: virtual_recipients.j2
    dest: /etc/postfix/virtual_recipients
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: postfix, config

- name: Create postfix main.cf file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: postfix, config

- name: Create postfix master.cf file
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: postfix, config

- name: Postmap virtual recipients, virtual_recipient_domains
  command: "{{ item }}"
  with_items:
    - postmap /etc/postfix/virtual_recipient_domains
    - postmap /etc/postfix/virtual_recipients
  notify: restart postfix
  changed_when: False
  tags: postfix, config

- name: Create smtpd.conf file
  template:
    src: smtpd.conf.j2
    dest: /etc/postfix/sasl/smtpd.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: postfix, config

- name: Open firewall port 25
  ufw:
    rule: allow
    port: '25'
    proto: tcp
  notify: restart ufw
  tags: postfix, config
