---

- name: Verificar OS
  fail:  msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"
  tags: always

- name: Set dbconfig_common questions
  debconf:
    name: dbconfig
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ dbconfig_common }}"
  tags: mailman3, setup

- name: Set mailman3 questions
  debconf:
    name: mailman3
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ mailman3_debconf }}"
  tags: mailman3, setup

- name: Set mailman3-web questions
  debconf:
    name: mailman3-web
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ mailman3_web_debconf }}"
  tags: mailman3, setup

- name: Install mailman3-full
  apt: name=mailman3-full state=present
  tags: mailman3, setup

- name: Copy mailman.cfg configuration template
  template:
    src: mailman.cfg.j2
    dest: "{{ mailman3_config_path }}/mailman.cfg"
    backup: yes
    owner: root
    group: list
    mode: 0640
  notify: restart mailman3
  tags: mailman3, config

- name: Copy mailman-web.py configuration template
  template:
    src: mailman-web.py.j2
    dest: "{{ mailman3_config_path }}/mailman-web.py"
    backup: yes
    owner: root
    group: www-data
    mode: 0640
  notify: restart mailman3-web
  tags: mailman3, config

- name: Copy mailman-hyperkitty.cfg configuration template
  template:
    src: mailman-hyperkitty.cfg.j2
    dest: "{{ mailman3_config_path }}/mailman-hyperkitty.cfg"
    backup: yes
    owner: root
    group: list
    mode: 0640
  notify: restart mailman3-web
  tags: mailman3, config

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
  tags: always

- name: Include task config_virtual_alias_domain.yml
  include_tasks: config_virtual_alias_domain.yml
  tags: always
