---

# - debug:
#     msg: "{{ item.kvm_new_vm_user_data.fqdn }}"
#   loop: "{{ new_hosts  }}"
#   loop_control:
#     label: "{{ item.name }}"
#
# - fail:

# tasks file for cloud-init-kvm
- name: Check if debian base image already exists
  stat:
    path: "{{ kvm_debian_base_img_dst }}/{{ kvm_debian_img_name }}"
  register: debian_base_image_exists

## Download debian qcow2
- name: Get debian cloud image
  get_url:
    url: "{{ kvm_debian_base_img_url }}/{{ kvm_debian_img_name }}"
    dest: "{{ kvm_debian_base_img_dst }}"
  when: debian_base_image_exists.stat.exists == 'false' | bool
  register: kvm_img

- name: Remove old use-data, meta-data and network-config files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/user-data
    - /tmp/meta-data
    - /tmp/network_config_static.cfg


- name: Include create_vm tasks
  include_tasks: create_vm.yml
  loop: "{{ new_hosts }}"
