---

- name: Verificar OS
  fail:  msg="This role is not supported in {{ansible_os_family}} OS"
  when: ansible_os_family != "Debian"

- name: Modificar configuração para modificar nameservers e domain-name
  template:
    src: dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf
    backup: yes
