---

- name: Reboot after update
  command: /sbin/shutdown -r 1 "Reboot"
  ###shutdown -r time (reboot after shutdown)
  ###The time argument specifies when to perform the shutdown operation.
  

###Wait 500 seconds, but only start checking after 60 seconds
- name: Wait for servers to become available
  wait_for_connection:  #Waits until remote system is reachable/usable
    delay: 60           #Number of seconds to wait before starting to poll.
    timeout: 500        #Maximum number of seconds to wait for.
    