---
# defaults file for mariadb

mariadb_packages:
  mariadb-server

mariadb_bind_address: 127.0.0.1
mariadb_default_port: 3306
mariadb_path: /etc/mysql
mariadb_config_path: /etc/mysql

mariadb_unix_socket: /var/run/mysqld/mysqld.sock
mariadb_user: root

#
# # * Logging and Replication
# #
# # Both location gets rotated by the cronjob.
# # Be aware that this log type is a performance killer.
# # As of 5.1 you can enable the log at runtime!
# #general_log_file       = /var/log/mysql/mysql.log
# #general_log            = 1
# #
# # Error log - should be very few entries.
# #
# log_error = /var/log/mysql/error.log
# #
# # Enable the slow query log to see queries with especially long duration
# #slow_query_log_file    = /var/log/mysql/mariadb-slow.log
# #long_query_time        = 10
# #log_slow_rate_limit    = 1000
# #log_slow_verbosity     = query_plan
# #log-queries-not-using-indexes
# #
# # The following can be used as easy to replay backup logs or for replication.
# # note: if you are setting up a replication slave, see README.Debian about
# #       other settings you may need to change.
# #server-id              = 1
# #log_bin                = /var/log/mysql/mysql-bin.log
# expire_logs_days        = 10
# #max_binlog_size        = 100M
# #binlog_do_db           = include_database_name
# #binlog_ignore_db       = exclude_database_name
#
#
# +------------------+----------+--------------+------------------+
# | File             | Position | Binlog_Do_DB | Binlog_Ignore_DB |
# +------------------+----------+--------------+------------------+
# | mysql-bin.000001 |      652 | wordpress    |                  |
# +------------------+----------+--------------+------------------+

# user: replication
# pw: slave_password


# CHANGE MASTER TO MASTER_HOST='10.0.0.21',MASTER_USER='replication', MASTER_PASSWORD='slave_password', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=652;
