---
# tasks file for mariadb

- name: Verificar OS
  fail:  msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"
  tags: always

- name: install mariadb
  apt: name="{{ mariadb_packages }}" state=present
  tags: mariadb, setup

- name: Make sure python3-pip is present
  apt: name=python3-pip state=present
  tags: mariadb, setup

- name: Make sure pymysql is present
  pip: name=pymysql state=present
  tags: mariadb, setup

# - name: Copy my.cnf file
#   template:
#     src: my.cnf.j2
#     dest: "{{ mariadb_config_path }}/my.cnf"
#     backup: yes
#     owner: root
#     group: root
#     mode: 0644
#   notify: restart mariadb
#   tags: mariadb, config

# DATABASES
#
# - name: Create databases
#   mysql_db:
#     db: wordpress
#     state: present
#     login_user: "{{ mariadb_user }}"
#     login_unix_socket: "{{ mariadb_unix_socket }}"
#   tags: mariadb, config

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mariadb_user }}"
    login_unix_socket: "{{ mariadb_unix_socket }}"
  tags: mariadb, config

# USERS
#
- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mariadb_user }}"
    login_unix_socket: "{{ mariadb_unix_socket }}"
  no_log: True
  tags: mariadb, config

# - name: del  user
#   mysql_user:
#     name: "{{ item.name }}"
#     state: absent
#     login_user: "{{ mariadb_user }}"
#     login_unix_socket: "{{ mariadb_unix_socket }}"
#   with_items: "{{ mariadb_users }}"
#   # no_log: True
#   tags: mariadb, config

- name: Create new user
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    priv: "{{ item.priv }}"
    state: present
    login_user: "{{ mariadb_user }}"
    login_unix_socket: "{{ mariadb_unix_socket }}"
  with_items: "{{ mariadb_users }}"
  # no_log: True
  tags: mariadb, config

# DEBUG
#
- debug:
    msg: "{{ item }}"
  with_items: "{{ mariadb_users }}"
  tags: debug
