---
- hosts: new
  become: true
  roles:
   - initial_setup

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: user
      prompt: "Username"
      private: no
    - name: user_password
      prompt: "Password"
      private: yes
      encrypt: sha512_crypt
      salt_size: 7
