---
# tasks file for cyrus-imap
# https://www.cyrusimap.org/quickstart.html

- name: Verificar OS
  fail:  msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"

################################ UTIILIZAR O MÓDULO user!!! ####################
# - name: Verificar se o grupo 'mail' existe
#   shell: getent group {{ cyrus_imap_default_group }} | awk -F':' '{print $1}'
#   register: group_mail_exists
#   ignore_errors: true
#   changed_when: False
#   tags: cyrus_imap, config
# ################################ UTIILIZAR O MÓDULO user!!! ####################
# - name: Message to inform if the mail group exists
#   debug: msg="GROUP {{ cyrus_imap_default_group }} EXISTS"
#   when: group_mail_exists.stdout == cyrus_imap_default_group
#   tags: cyrus_imap, debug
################################ UTIILIZAR O MÓDULO user!!! ####################
# - name: Criar grupo 'mail'
#   command: groupadd -fr {{ cyrus_imap_default_group }}
#   when: group_mail_exists.stdout != cyrus_imap_default_group
#   tags: cyrus_imap, config
################################ UTIILIZAR O MÓDULO user!!! ####################
# - name: verificar se existe o utilizador cyrus
#   shell: getent passwd {{ cyrus_imap_default_user }} | awk -F':' '{print $1}'
#   register: cyrus_user_exists
#   ignore_errors: true
#   changed_when: False
#   tags: cyrus_imap, config
# ################################ UTIILIZAR O MÓDULO user!!! ###################
# - name: Message to inform if the cyrus user exists
#   debug: msg="USER {{ cyrus_imap_default_user }} EXISTE!!"
#   when: cyrus_user_exists.stdout == cyrus_imap_default_user
#   tags: cyrus_imap, debug

#TODO: utilizar variável default_cyrus_user
#The var/lib/imap directory above is an example.
#Use the same directory specified in the configdirectory option in imapd.conf(5).
################################ UTIILIZAR O MÓDULO user!!! ####################
# - name: Create user 'cyrus' and add it to mail, sasl group
#   command: useradd -c "Cyrus IMAP Server" -d /var/lib/cyrus -G {{ cyrus_imap_default_group }},{{ cyrus_imap_default_sasl_group }} -s /bin/bash -r cyrus
#   when: cyrus_user_exists.stdout != cyrus_imap_default_user
#   tags: cyrus_imap, config

- name: Criar grupo 'mail'
  group:
    name: "{{ cyrus_imap_default_group }}"

- name: Create user 'cyrus' and add it to mail, sasl group
  user:
    name: cyrus
    comment: Cyrus IMAP Server
    groups: "{{ cyrus_imap_default_group }},{{ cyrus_imap_default_sasl_group }}"
    home: /var/lib/cyrus
    shell: /bin/bash
    system: 'yes'

- name: Install cyrus-imap packages
  apt: name="{{ cyrus_imap_packages }}" state=present
  notify: restart cyrus-imap
  tags: cyrus_imap, setup

- name: Copy cyrus.conf configuration file
  template:
    src: cyrus.conf.j2
    dest: /etc/cyrus.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart cyrus-imap
  tags: cyrus_imap, config

- name: Copy imapd.conf configuration file
  template:
    src: imapd.conf.j2
    dest: /etc/imapd.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart cyrus-imap
  tags: cyrus_imap, config

# All of the Postfix processes that use chroot change their root directory
# to the directory specified in the queue_directory parameter, which is normally
# /var/spool/postfix.
# https://www.oreilly.com/library/view/postfix-the-definitive/0596002122/ch04s08.html
# chroot...
- name: Mount directory /run/cyrus
  mount:
    path: /var/spool/postfix/var/run/cyrus
    src: /run/cyrus
    opts: bind,rw
    state: mounted
    fstype: none
  tags: cyrus_imap, config

# chroot ...
- name: Mount directory /run/saslauthd
  mount:
    path: /var/spool/postfix/var/run/saslauthd
    src: /run/saslauthd
    opts: bind,rw
    state: mounted
    fstype: none
  tags: cyrus_imap, config

- name: Add group mail to postfix user
  user:
    name: postfix
    groups: mail
    append: true
  tags: cyrus_imap, config

- name: Open port 143(imap) on ufw
  ufw: rule=allow port='143' proto=tcp
  notify: restart ufw
  tags: cyrus_imap, config
