---
- name: "Installing additional software"
  apt: 
    name={{ packages  }}
  vars:
    packages:
    - dnsutils
    - git
    - tree
    - aptitude
    - yum

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: do a ping
  ping:

- name: Copy txt file
  copy:
    src: ../files/doc.txt
    dest: /home/{{ ansible_user }}/doc1.txt

- name: Copy another doc
  copy:
    content: 'some content'
    dest: /home/{{ ansible_user }}/doc2.txt
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
- name: debug
  debug:
    msg: "foo -> {{foo}}"

- name: Reboot after update
  command: /sbin/shutdown -r 1 "Reboot"
  ###shutdown -r time (reboot after shutdown)
  ###The time argument specifies when to perform the shutdown operation.
  

###Wait 500 seconds, but only start checking after 60 seconds
- name: Wait for servers to become available
  wait_for_connection:  #Waits until remote system is reachable/usable
    delay: 60           #Number of seconds to wait before starting to poll.
    timeout: 500        #Maximum number of seconds to wait for.