---
keepalived_vrrp_instance:
  - name: VI_1
    state: BACKUP
    interface: enp1s0
    virtual_router_id: 51
    priority: 100
    advert_int: 1
    authentication:
      auth_type: PASS
      auth_pass: secretVRRP
    virtual_ipaddress:
      - 10.0.0.100/24



# https://github.com/Aidaho12/haproxy-wi/issues/224
# groupadd -r keepalived_script
# useradd -r -s /sbin/nologin -g keepalived_script -M keepalived_script


# https://www.redhat.com/sysadmin/advanced-keepalived
#
# vrrp_script keepalived_check {
#       script "/usr/local/bin/keepalived_check.sh"
#       interval 1
#       timeout 5
#       rise 3
#       fall 3
# }
#
# vrrp_instance VI_1 {
#       state MASTER
#       interface eth0
#       virtual_router_id 51
#       priority 244
#       advert_int 1
#       authentication {
#          auth_type PASS
#          auth_pass 12345
#       }
#       virtual_ipaddress {
#          192.168.122.200/24
#       }
#       track_script {
#          keepalived_check
#       }
#       notify "/usr/local/bin/keepalived_notify.sh"
# }

# /usr/local/bin/keepalived_check.sh -> chown keepalived_script
# #!/bin/bash
#
# /usr/bin/ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1

# /usr/local/bin/keepalived_notify.sh -> chown keepalived_script
# #!/bin/bash
#
# echo $(date) " - $1 $2 has transitioned to the $3 state with a priority of $4" >> /var/run/keepalived_status

# touch /var/run/keepalived_status -> chown keepalived_script

# UFW
# sudo ufw allow 112/udp
# sudo ufw allow from 224.0.0.18
# sudo ufw allow to 224.0.0.18

# Ativar falha
# iptables -A OUTPUT -d 1.1.1.1 -j DROP

# Desativar falha
# iptables -D OUTPUT -d 1.1.1.1 -j DROP
