---
keepalived_vrrp_instance:
  - name: VI_1
    state: Master
    interface: enp1s0
    virtual_router_id: 51
    priority: 255
    advert_int: 1
    authentication:
      auth_type: PASS
      auth_pass: 12345
    virtual_ipaddress:
      - 10.0.0.100/24
