---
# tasks file for cyrus-sasl2

- name: Verificar OS
  fail:  msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"
  tags: cyrus_sasl2

- name: Install sasl2 packages
  apt: name="{{ sasl2_packages }}" state=present
  notify: restart sasl
  tags: cyrus_sasl2, setup

#TODO: utilizar variável default_sasl_group
- name: Verificar se o grupo 'sasl' existe
  shell: getent group {{ default_sasl_group }} | awk -F':' '{print $1}'
  register: group_sasl_exists
  ignore_errors: true
  changed_when: False
  tags: cyrus_sasl2, config

# '-r' : create a system account
- name: Criar grupo 'sasl'
  command: groupadd -fr {{ default_sasl_group }}
  when: group_sasl_exists.stdout != default_sasl_group
  tags: cyrus_sasl2, config

- name: Adicionar o utilizado postfix ao grupo sasl
  user: name=postfix groups=sasl append=yes
  tags: cyrus_sasl2, config

- name: Modificar configuração do saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: true
  notify: restart sasl
  with_items:
    - regexp: "^START="
      line: "START=yes"
    - regexp: "^MECHANISMS="
      line: "MECHANISMS=\"sasldb\""
  tags: cyrus_sasl2, config

- name: flush handlers
  meta: flush_handlers

# Estes utilizar vai ser o admin?? Mudar linha admin=cyrus no cyrus.conf
- name: Criar admin do IMAP dentro do SASL
  shell: set -o pipefail && echo {{ sasl_default_imap_admin.password }} | saslpasswd2 -p -c {{ sasl_default_imap_admin.name }}
  args:
    executable: /bin/bash
  changed_when: False
  tags: cyrus_sasl2, config

- name: Testar autenticação saslauthd
  shell: set -o pipefail &&  testsaslauthd -u cyrus -p qwerty  | awk -F' ' '{print $2}'
  args:
    executable: /bin/bash
  register: saslauthd_cyrus_check
  changed_when: False
  tags: cyrus_sasl2, debug

- name: Verificar se a autenticação com o novo utilizador deu OK
  debug: msg="0 OK Success."
  when: saslauthd_cyrus_check.stdout == "OK"
  tags: cyrus_sasl2, debug

- name: Verificar se a autenticação com o novo utilizador deu NO
  debug: msg="0 NO authentication failed"
  when: saslauthd_cyrus_check.stdout == "NO"
  tags: cyrus_sasl2, debug

- name: Criar utilizadores dentro do SASL
  shell: set -o pipefail && echo {{ item.password }} | saslpasswd2 -p -c {{ item.name }}@{{ item.domain }}
  args:
    executable: /bin/bash
  with_items: "{{ sasl_users }}"
  when: sasl2_create_users
  tags: cyrus_sasl2, config
