---
#TODO: utilizar variável default_sasl_group
- name: Verificar se o grupo 'sasl' existe
  shell: getent group sasl | awk -F':' '{print $1}'
  register: group_sasl_exists
  ignore_errors: true

- debug: msg="GROUP 'sasl' EXISTS"
  when: group_sasl_exists.stdout == "sasl"

#TODO: utilizar variável default_sasl_group
#-r: create a system account
- name: Criar grupo 'sasl'
  shell: groupadd -fr sasl
  when: group_sasl_exists.stdout != "sasl"

#TODO: utilizar variável default_mail_group
- name: Verificar se o grupo 'mail' existe
  shell: getent group mail | awk -F':' '{print $1}'
  register: group_mail_exists
  ignore_errors: true

- debug: msg="GROUP 'mail' EXISTS"
  when: group_mail_exists.stdout == "mail"

#TODO: utilizar variável default_mail_group
#-r: create a system account
- name: Criar grupo 'mail'
  shell: groupadd -fr mail
  when: group_mail_exists.stdout != "mail"

#TODO: utilizar variável default_cyrus_user
- name: verificar se existe o utilizador cyrus
  shell: getent passwd cyrus | awk -F':' '{print $1}'
  register: cyrus_user_exists
  ignore_errors: true

- debug: msg="USER 'cyrus' EXISTE!!"
  when: cyrus_user_exists.stdout == "cyrus"

#TODO: utilizar variável default_cyrus_user
#The var/lib/imap directory above is an example. Use the same directory specified in the configdirectory option in imapd.conf(5).
- name: Criar utilizador cyrus e adicionar ao grupo mail
  shell: useradd -c "Cyrus IMAP Server" -d /var/lib/cyrus -G mail,sasl -s /bin/bash -r cyrus
  when: cyrus_user_exists.stdout != "cyrus"


- name: Install sasl2 packages
  apt:
    name: "{{sasl2_packages}}"
    update_cache: true
    state: present
  notify:
    - restart sasl

- name: Install cyrus-imap packages
  apt:
    name: "{{ cyrus_imap_packages }}"
    update_cache: true
    state: present
  notify:
    - restart cyrus-imap

- name: Mudar configuração do saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: true
  notify: restart sasl
  with_items:
    - regexp: "^START="
      line: "START=yes"
    - regexp: "^MECHANISMS="
      line: "MECHANISMS=\"sasldb\""

- name: flush handlers
  meta: flush_handlers


#TODO utilizar variáveis para o user/pw(imap_admin_user/imap_admin_password []??])
# Estes utilizar vai ser o admin?? Mudar linha admin=cyrus no cyrus.conf
- name: Criar utilizador IMAP dentro do SASL
  shell: echo qwerty | saslpasswd2 -p -c cyrus

#TODO verificar se foi feita a autenticação com sucesso -> 0: OK "Success."
- name: Testar autenticação saslauthd
  shell: testsaslauthd -u cyrus -p qwerty  | awk -F' ' '{print $2}'
  become: true
  register: saslauthd_cyrus_check

- name: Verificar se a autenticação com o novo utilizador deu OK
  debug: msg="0 OK Success."
  when: saslauthd_cyrus_check.stdout == "OK"

- name: Verificar se a autenticação com o novo utilizador deu NO
  debug: msg="0 NO authentication failed"
  when: saslauthd_cyrus_check.stdout == "NO"

#- debug: msg="{{saslauthd_cyrus_check}}"

- name: Copy cyrus.conf conf file
  template:
    src: cyrus.normal.conf.j2
    dest: /etc/cyrus.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart cyrus-imap

- name: Copy imapd.conf conf file
  template:
    src: imapd.normal.conf.j2
    dest: /etc/imapd.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: restart cyrus-imap
