---
# vars for mailservers group

#
# postfix
postfix_use_ssl: False
postfix_smtpd_tls_key_file: /etc/ssl/certs/mail.alcafaz.test.key.pem
postfix_smtpd_tls_cert_file: /etc/ssl/certs/mail.alcafaz.test.cert.pem
postfix_smtpd_tls_CAfile: /etc/ssl/certs/mail.alcafaz.test.ca.pem
postfix_mynetworks: 127.0.0.0/8 192.168.100.0/24
postfix_virtual_domain_name: alcafaz.test
postfix_root_address: admin@{{ postfix_virtual_domain_name }}
postfix_use_spf: True
postfix_use_mailman3: False
postfix_virtual_recipients:
  - name: diogo
    domain: "{{ postfix_virtual_domain_name }}"
  - name: admin
    domain: "{{ postfix_virtual_domain_name }}"
  - name: marcia
    domain: "{{ postfix_virtual_domain_name }}"
  - name: mailman3web
    domain: "{{ postfix_virtual_domain_name }}"

#
# cyrus_imap
cyrus_imap_tls:
  use: False
  tls_server_cert: /etc/ssl/certs/mail.alcafaz.test.cert.pem
  tls_server_key: /etc/ssl/certs/mail.alcafaz.test.key.pem
  tls_client_ca_file: /etc/ssl/certs/csr/mail.alcafaz.test.ca.pem
  tls_client_ca_dir: /etc/ssl/certs
  tls_session_timeout: 1440

#
# sasl2
sasl2_create_users: True
sasl_users:
  - name: diogo
    password: qwerty
    domain: alcafaz.test
  - name: admin
    password: qwerty
    domain: alcafaz.test
  - name: marcia
    password: qwerty
    domain: alcafaz.test
  - name: mailman3web
    password: qwerty
    domain: alcafaz.test
