---

bind_zones:
  - name: alcafaz.test
    reverse: 100.168.192
    type: primary
    serial: 2021030300
    admin_email: admin #admin zone email
    primary: 192.168.100.5  #primary nameserver
    mail_servers: #mx records
    - name: mail
      preference: 10
    nameservers:
      - ns1.dd.test.
    records:
      - { name: ns1,    forward: 192.168.100.5,   type: A, rev: 5  }
      - { name: mail,   forward: 192.168.100.10,  type: A, rev: 10 }
      - { name: '@',    forward: 192.168.100.1,   type: A, rev: 1 }
    bind_acl_trusted_networks:
      - 192.168.100.0/24
  # - name: other.test
