---
- hosts: ns1Alcafaz
  become: true
  roles:
  - dns_bind

  vars:
    bind_zones:
      - name: alcafaz.test
        reverse: 100.168.192
        type: primary
        serial: 2020012600
        admin_email: hostmaster #admin zone email
        primary: 192.168.100.5  #primary nameserver
        mail_servers: #mx records
          - name: mail
            preference: 10
        nameservers:
          - ns1.dd.test.
        records:
          - { name: ns1,    forward: 192.168.100.5,   type: A, rev: 5  }
          - { name: mail,   forward: 192.168.100.10,  type: A, rev: 10 }
          - { name: '@',    forward: 192.168.100.1,   type: A, rev: 1 }

    bind_acl_trusted_networks:
      - 192.168.1.0/24
      - 192.168.100.0/24

#TODO log separado do bind
#TODO 'bind_zone' mais completo (P.EX. add email, ttl, ns, txt)
  # bind_zones:
  #   - name: dd.test
  #     type: master
  #     reverse: 0.0.10
  #     mx: mail.dd.test
  #     txt:
  #       - "some text"
  #       - "some text"
  #     records:
  #       - { name: ns1,   forward: 10.0.0.11,     type: A, rev: 11 }
  #       - { name: lb02,   forward: 10.0.0.12,     type: A, rev: 12 }
