- hosts: mailAlcafaz
  become: true

  roles:
   - apache2

  vars:
    apache2_vhost:
      - name: unts.xyz
        server_name: www.unts.xyz
        conf_name: unts.xyz.conf
        port: 80
    apache2_create_vhost: True
