---
# vars file for loadbalancer

keepalived_vrrp_instance:
  - name: VI_1
    state: Master
    interface: enp1s0
    virtual_router_id: 51
    priority: 255
    advert_int: 1
    authentication:
      auth_type: PASS
      auth_pass: 12345
    virtual_ipaddress:
      - 10.0.0.100/24

haproxy_global:
    log:
      - /dev/log    local0
      - /dev/log    local1 notice
    user: haproxy
    group: haproxy

haproxy_defaults:
  mode: http
  log: global
  options:
     - name: httplog
     - name: dontlognull
  timeouts:
    - name: connect
      time: 5000
    - name: client
      time: 50000
    - name: server
      time: 50000
  errorfile:
    - code: 400
      file: /etc/haproxy/errors/400.http
    - code: 403
      file: /etc/haproxy/errors/403.http
    - code: 408
      file: /etc/haproxy/errors/408.http
    - code: 500
      file: /etc/haproxy/errors/500.http
    - code: 502
      file: /etc/haproxy/errors/502.http
    - code: 503
      file: /etc/haproxy/errors/503.http
    - code: 504
      file: /etc/haproxy/errors/504.http

haproxy_listen:
  name: stats
  bind:
    - ip: '*'
      port: 8080
  stats:
    - name: enable
    - name: hide-version
    - name: uri
      uri: /haproxy?stats
    - name: refresh
      time: 10s

haproxy_frontend:
    name: loadbalancer_haproxy
    mode: http # tcp, http
    balance: roundrobin # roundrobin, static-rr, leastconn, source, uri, url_param, hdr(<name>), rdp-cookie, rdp-cookie(name)
    bind:
      - ip: '*' # set '*' for all
        port: 80
    default_backend: webservers

haproxy_backend:
  name: webservers
  servers:
    - name: web01
      bind:
        - ip: 10.0.0.21
          port: 80
      check: check
      weight: 50
    - name: web02
      bind:
        - ip: 10.0.0.22
          port: 80
      check: check
      weight: 50
  balance: roundrobin
