---

- name: Check current timezone
  shell: cat /etc/timezone
  register: current_timezone

- name: Set timezone variables
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: current_timezone.stdout != timezone
  notify:
    - update timezone

#- debug:
#    msg: 
#      - "{{ timezone }}"
#      - "{{ current_timezone.stdout }}"
#  when: current_timezone.stdout != timezone