---
- name: Install apache web server
  apt:
    pkg: apache2
    state: present
    update_cache: true

#ansible-playbook -K playbook.yml -l app
# -l limita a execução do playbook apenas ao grupo 'app'
# -K sudo user

- name: Push future foo virtual host configuration
  copy:
    src: ../files/foo/foo.conf
    dest: /etc/apache2/sites-available/foo.conf
    mode: 0640 
    #   User   | Group | Other
    #   r+w    | r     |    

    #chmod 777 
    #    User  | Group | Other
    #   r+w+x  | r+w+x | r+w+x


- name: Push future bar virtualhost configuration
  copy: 
    src: ../files/bar/bar.conf
    dest: /etc/apache2/sites-available/bar.conf

- name: Activates our virtualhost
  command: a2ensite foo

- name: Activates bar virtualhost
  command: a2ensite bar

- name: Check that our config is valid
  command: apache2ctl configtest


- name: Deactivates the defautl virtualhost
  command: a2dissite 000-default

- name: Deactivates the defautl ssl virtualhost
  command: a2dissite default-ssl
  notify:
    restart apache

- name: Disable the default virtualhost
  file:
    dest: /etc/apache2/sites-enabled/default
    state: absent
  notify:
    - restart apache

- name: Remove app1.conf file
  file:
    dest: /etc/apache2/sites-enabled/app1
    state: absent
  notify:
    - restart apache

- name: Disable the default ssl virtualhost
  file:
    dest: /etc/apache2/sites-enabled/default-ssl
    state: absent
  notify:
    - restart apache

- name: Activates foo virtualhost
  file:
    src: /etc/apache2/sites-available/foo.conf
    dest: /etc/apache2/sites-enabled/foo
    state: link
  notify:
    - restart apache

- name: Activates bar virtualhost
  file:
    src: /etc/apache2/sites-available/bar.conf
    dest: /etc/apache2/sites-enabled/bar
    state: link
  notify:
    - restart apache

- name: Copy foo html file
  copy:
    src: ../files/foo/index.html
    dest: /var/www/foo/

- name: Copy bar html file
  copy:
    src: ../files/bar/index.html
    dest: /var/www/bar/