---
# vars for ns1 host - bind9

bind_zones:
  - name: alcafaz.test
    reverse: 100.168.192
    type: primary
    serial: 2021030800
    admin_email: admin #admin zone email
    mail_servers: #mx records
    - name: mail
      preference: 10
    nameservers:
      - ns1.dd.test.
    records:
      - { name: ns1,    forward: 192.168.100.5,   type: A, rev: 5  }
      - { name: mail,   forward: 192.168.100.10,  type: A, rev: 10 }
      - { name: web01,  forward: 192.168.100.15,  type: A, rev: 15 }
      - { name: '@',    forward: 192.168.100.15,  type: A, rev: 15 }
      - { name: 'www',  forward: alcafaz.test,    type: CNAME }
bind_acl_trusted_networks:
  - 192.168.100.0/24
  # - name: other.test
