---
# vars file for Bind setup


bind_default_forward_dns: opendns
bind_forwarders:
  opendns:
    primary: 208.67.222.222
    secondary: 208.67.220.220
  google:
    primary: 8.8.8.8
    secondary: 8.8.4.4
  cloudflare:
    primary: 1.1.1.1
    secondary: 1.0.0.1

bind_zones_path: /var/lib/bind/zones
bind_soa_email: admin.{{ bind_domain }}
bind_log_path: /var/log/named\
bind_refresh: 604800
bind_retry: 86400
bind_expire: 2419200
bind_negative_cache_ttl: 604800
bind_ttl: 604800
