- hosts: new
  become: true

  roles:
    - initial_setup

  vars_prompt:
    - name: user
      prompt: "Username"
      private: no
    - name: user_password
      prompt: "Password"
      private: yes
      encrypt: sha512_crypt
      salt_size: 7


  vars:
    supersede_dhcp: False
    hostname_name: rpi
    # user: admin
    hostname_domain_name:
    # dhcp_config_ns1: 192.168.100.5
    # dhcp_config_ns2: 1.1.1.1
    # dhcp_config_domain_search: alcafaz.test
    packages_to_install:
      - sudo
      - aptitude
      - ufw
      - curl
      - dnsutils
