---
- hosts: localhost
  become: false
  gather_facts: no
  roles:
  - kvm
  vars:
    kvm_add_new_host: True
    # Informação sobre o novo host a adicionar à network

    host:
      mode: add
      name: ns1.alcafaz.test
      ip: '192.168.100.5'
      mac: '52:54:00:bc:89:40'
      network: alcafaz.test
