---
- hosts: localhost
  become: false
  gather_facts: no
  roles:
  - kvm
  vars:
    kvm_add_new_host: true
    kvm_dhcp_hosts:
      - { name: ns2.alcafaz.test, mac: 52:54:00:42:76:fc , ip: 192.168.100.6 }
