- hosts: webDD
  become: true

  roles:
    - apache2
    - mariadb
    - wordpress

  vars:
    # Apache2
    #
    apache2_vhost:
      - name: dd.test
        server_name: www.dd.test
        conf_name: dd.test.conf
        port: 80
    apache2_create_vhost: True
    # Mariadb
    #
    mariadb_databases:
      - name: wordpress
    mariadb_users:
      - name: wp
        password: qwerty
        host: localhost
        priv: "wordpress.*:ALL,GRANT"
    # WordPress
    #
    wp_db_name: wordpress
    wp_db_user: wp
    wp_db_password: qwerty
    wp_db_host: localhost
    wp_table_prefix: wp_
    wp_home: http://dd.test
    wp_siteurl: http://dd.test

# {{ wp_secret_key}}
# {{ wp_secure_auth_key }}
# {{ wp_logged_in_key }}
# {{ wp_nonce_key }}
# {{ wp_auth_salt }}
# {{ wp_secure_auth_salt }}
# {{ wp_logged_in_salt }}
# {{ wp_nonce_salt }}
