---
- name: Modificar configuração do dhclient.conf para modificar nameservers e domain-name
  template:
    src: dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags: dhcp_config, config
