---
- name: Install essential packages
  apt:
    name: "{{ packages_to_install }}"
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Update all packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
