---
#faz sentido???? se não está instaladi, não vou consigar ligar-me por ssh e verficar se está instalado!!!
- name: ensure ssh is installed
  apt:
    pkg: openssh-server
    state: present
    update_cache: true
    cache_valid_time: 3600
  notify: restart ssh

- name: Update SSH configuration to be more secure
  lineinfile:
    dest: "{{ ssh_dir_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    "{{ ssh_config }}"
  notify: restart ssh
  when: ansible_distribution == 'Debian'


### TODO:
  #  - permitir/proibir utilizador a fazer ligar-se por ssh
