---
- name: Check current timezone
  command: cat /etc/timezone
  register: current_timezone
  tags: timezone, config

- name: Update timezone file - '/etc/timezone'
  copy:
    content: "{{ timezone_local }}"
    dest: "{{ timezone_default_path }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: current_timezone.rc != timezone
  notify: update timezone
  tags: timezone, config

- name: Check ntp servers
  command: grep -c "^NTP=" /etc/systemd/timesyncd.conf # 1 if true, 0 if false
  register: current_ntp
  #ignore_errors: true
  failed_when: current_ntp.rc != 1 and current_ntp.rc != 0
  changed_when: False
  tags: timezone, config

- name: Add ntp servers to /etc/systemd/timesyncd.conf
  lineinfile:
    dest: "{{ timezone_ntp_default_path }}"
    regexp: "^NTP="
    line: "NTP={{ timezone_ntp_server }}"
  when: current_ntp.stdout == '0'
  notify: enable network time sync
  tags: timezone, config
