---
- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add new super user
  user:
    name: "{{ user }}"
    password: "{{ user_password }}"
    groups: sudo
    append: yes
    state: present
    shell: /bin/bash
    update_password: always

- name: Add SSH key for new super user
  authorized_key:
    user: "{{ user }}"
    key: "{{  lookup('file',item) }}"
  with_items: "{{ user_public_key_path }}"

#- name: Disable user password
#  shell: passwd -d "{{ user }}"

#- name: Expire user password
#  shell: passwd -e "{{ user  }}"

- name: Remove default user
  user:
    name: "{{ user_default }}"
    state: absent
    remove: yes
