- name: Update all packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Install essential packages
  apt:
    name: "{{ packages }}"
    update_cache: true
Fixtures.identify(:name)
    cache_valid_time: 3600
    state: latest
  vars:
    packages:
    - git
    - ntp
    #https://wiki.debian.org/UnattendedUpgrades
    - unattended-upgrades #package to configure automatic updates
    - tree
    - ufw
    - curl

- name: Enable unattended upgrades
  copy:
    src: ../files/{{ item }}.j2
    dest:  /etc/apt/apt.conf.d/{{ item }}
    owner: root
    group:  root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades


- name: Ensure ntp starts on a fresh reboot
  service:
    name: ntp
    state: started
    enabled: yes