---

- name: Verificar OS
  fail: msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"


- debug:
   msg:
  loop: "{{ bind_zones }}"

- debug:
   msg:
  loop: "{{ records | dict2items }}"

- name: Exterminate mankind
  pause:
    prompt: Please confirm you want to exterminate mankind! Press return to continue. Press Ctrl+c and then "a" to abort

- name: install bind
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bind9
      - bind9utils
      - bind9-doc
  tags: [ install ]

- name: Copy named conf log file
  template:
    src: named.conf.log.j2
    dest: /etc/bind/named.conf.log
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: restart named
  tags: [ config ]

- name: Copy named conf file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: restart named
  tags: [ config ]


- name: debug shit
  debug:
    msg: "{{ bind_zones[0].name }}"

- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    backup: yes
    owner: root
    group: bind
    mode: 0640
  notify: restart named
  tags: [ config ]

- name: Make zones directory
  file:
    path: /var/lib/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy default zone data
  template:
    src: default-zone-data.j2
    dest: /var/lib/bind/zones/default-zone-data
    owner: root
    group: bind
    mode: 0640
  tags: [zone_defaults]

- name: Copy alcafaz.test forward file
  template:
    src: db.forward.alcafaz.test.j2
    dest: /var/lib/bind/zones/db.{{ bind_domain }}
    owner: root
    group: bind
    mode: 0640
  with_dict: "{{ records }}"
  notify: restart named
  tags: [ zone_records ]

- name: Copy alcafaz.test reverse file
  template:
    src: db.reverse.alcafaz.test.j2
    dest: /var/lib/bind/zones/db.{{ rev_domain }}
    owner: root
    group: bind
    mode: 0640
  with_dict: "{{ records }}"
  notify: restart named
  tags: [ zone_records ]

- name: Open firewall port
  ufw:
    rule: allow
    port: '53'
