---
- name: Verificar OS
  fail: msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"
  tags: always

- name: install bind
  apt: name="{{ bind_packages }}" state=present
  tags: bind9, setup

- name: Copy named.conf file
  template:
    src: named.conf.j2
    dest: "{{ bind_config_path }}/named.conf"
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: restart named
  tags: bind9, config

- name: Copy named.conf.log file
  template:
    src: named.conf.log.j2
    dest: "{{ bind_config_path }}/named.conf.log"
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: restart named
  tags: bind9, config

- name: Copy named.conf.options file
  template:
    src: named.conf.options.j2
    dest: "{{ bind_config_path }}/named.conf.options"
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: restart named
  tags: bind9, config

- name: Copy named.conf.local file
  template:
    src: named.conf.local.j2
    dest: "{{ bind_config_path }}/named.conf.local"
    backup: yes
    owner: root
    group: bind
    mode: 0640
  notify: restart named
  tags: bind9, config

- name: Create zones directory
  file:
    path: "{{ bind_zones_path }}"
    state: directory
    owner: root
    group: bind
    mode: 0750
  tags: bind9, zone_config

- name: Create log directory
  file:
    path: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: 0744
  tags: bind9, config

- name: Copy zone forward file
  template:
    src: db.forward.zone.j2
    dest: "{{ bind_zones_path }}/db.{{ item.name }}"
    owner: root
    group: bind
    mode: 0640
  with_items: "{{ bind_zones }}"
  notify: [ restart named ]
  tags: bind9, zone_config

- name: Copy reverse zone file
  template:
    src: db.reverse.zone.j2
    dest: "{{ bind_zones_path }}/db.{{ item.reverse }}.in-addr.arpa"
    owner: root
    group: bind
    mode: 0640
  with_items: "{{ bind_zones }}"
  notify: restart named
  tags: bind9, zone_config

- name: Open firewall port
  ufw: rule=allow port='53'
  tags: bind9, config
