---

- name: Verificar OS
  fail: msg="This role is not supported in {{ ansible_os_family }} OS"
  when: ansible_os_family != "Debian"

# - debug:
#    msg:
#      # - "{{ item.records.name }}"
#      # - "Zone name: {{ item.0.name }}"
#      # - "Zone type: {{ item.0.type }}"
#      # - "Record name: {{ item.1.name }}"
#     # - "item[0] -> {{ item[0] }}"
#     # - "item[1] -> {{ item[1] }}"
#   with_items: "{{ bind_zones  }}"
#   # with_subelements:
#   # - "{{ bind_zones }}"
#     # - records
#   # run_once: true
#   # loop_control:
#     # label: "{{ item.0.name }}"
#   tags: [ debug ]
# #
# # - fail:

# - name: Include task list in play
#   import_tasks: set_bind_serial.yml
#   tags: [ update_serial , zone_records, config_named, test ]

# - name: Run serial script to update zone serial
#   script:
#     cmd: files/serial.sh
#   tags: [ update_serial ]

# - name: Exterminate mankind
#   pause:
#     prompt: Please confirm you want to exterminate mankind! Press return to continue. Press Ctrl+c and then "a" to abort

- name: install bind
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages: [ bind9, bind9utils, bind9-doc ]
  tags: [ install ]

- name: Copy named conf file
  template:
    src: named.conf.j2
    dest: "{{ bind_config_path }}/named.conf"
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: [ restart named ]
  tags: [ config_named ]

- name: Copy named conf log file
  template:
    src: named.conf.log.j2
    dest: "{{ bind_config_path }}/named.conf.log"
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: [ restart named ]
  tags: [ config_named ]

- name: Copy named conf options file
  template:
    src: named.conf.options.j2
    dest: "{{ bind_config_path }}/named.conf.options"
    backup: yes
    owner: root
    group: bind
    mode: 0660
  notify: [ restart named ]
  tags: [ config_named ]

- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: "{{ bind_config_path }}/named.conf.local"
    backup: yes
    owner: root
    group: bind
    mode: 0640
  notify: [ restart named ]
  tags: [ config_named ]

- name: Make zones directory
  file:
    path: "{{ bind_zones_path }}"
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Make log directory
  file:
    path: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: 0744

- name: Copy zone forward file
  template:
    src: db.forward.zone.j2
    dest: "{{ bind_zones_path }}/db.{{ item.name }}"
    owner: root
    group: bind
    mode: 0640
  with_items: "{{ bind_zones }}"
  notify: [ restart named ]
  tags: [ zone_records, test ]

- name: Copy alcafaz.test reverse file
  template:
    src: db.reverse.zone.j2
    dest: "{{ bind_zones_path }}/db.{{ item.reverse }}.in-addr.arpa"
    owner: root
    group: bind
    mode: 0640
  with_items: "{{ bind_zones }}"
  notify: [restart named ]
  tags: [ zone_records ]


- name: Open firewall port
  ufw:
    rule: allow
    port: '53'
