---

# {% for host in foo_item %}
# {% if host.name == item.name %}
# {{ host.serial | string | indent(12, True) }}     ; Serial
# {% endif %}
# {% endfor %}


#
# if current_day == current_serial_date
#   bind_current_serial + 1
# else
#   bind_serial = bind_new_serial
#
#

# - debug:
#     msg:
#       - "{{ bind_serial }}"

- name: get new serial (yyyymmdd)
  shell: echo $(date +%Y%m%d00)
  register: new_serial
  changed_when: False

- name: get curr serial
  shell: cat /var/lib/bind/zones/db.{{ item.name }} | grep '; Serial' | awk '{ print $1 }'
  register: r_serial
  with_items: "{{ bind_zones }}"

- name: get serial to list
  set_fact:
    foo_item: "{{ foo_item|default([]) + [ {'name': item.item.name, 'serial': item.stdout} ] }}"
    # foo_item: "{{ r_serial.results | map(attribute='stdout') | list }}"
  with_items: "{{ r_serial.results }}"

# - set_fact:
#     bar_item: "{{ bar_item|default([]) + [ {'name': item.name, 'serial': item.serial | int +1} ] }}"
#   with_items: "{{ foo_item }}"
#   when: item.serial[:8] == new_serial.stdout[:8]

- set_fact: "x.name:  {{ y.serial if (x.name == y.name) }}"
  with_items:
    - x: "{{ bind_zones }}"
    - y: "{{ foo_item }}"

- fail:

- set_fact:
    xyz_item: "{{ xyz_item|default([]) + [ {'name': item.name, 'serial': new_serial.stdout if (item.serial[:8] != new_serial.stdout[:8]) else item.serial | int +1 } ] }}"
  with_items: "{{ foo_item }}"
  # when: item.serial[:8] != new_serial.stdout[:8]



- debug: msg="{{ item.serial }}"
  with_items: "{{ xyz_item }}"

# - fail:

# - name:  check if zone file exists
#   stat:
#     path: "{{ bind_zones_path }}/{{ item.name }}"
#   register: bind_default_zone_file

# - name: get current date (yyyymmdd)
#   shell: echo $(date +%Y%m%d)
#   register: current_day
#   changed_when: False
#
# - name: get new serial based on date (yyyymmddxx)
#   shell: echo $(date +%Y%m%d00)
#   register: bind_new_serial
#   changed_when: False
#
# - name: set new serial based on current date
#   set_fact:
#     bind_serial: "{{ bind_new_serial.stdout }}"
#
# - debug: msg="{{ bind_serial [:8]}}"
#
#
#
# - name: block to increment current serial
#
#   block:
#     - name: current serial date
#       shell: cat /var/lib/bind/zones/default-zone-data | grep '; Serial' | awk '{ print $1 }' | head -c 8
#       register: bind_current_serial_date
#       changed_when: False
#
#     - name: get current serial
#       shell: cat /var/lib/bind/zones/default-zone-data | grep '; Serial' | awk '{ print $1 }'
#       register: bind_current_serial
#       changed_when: False
#
#     - name: increment current serial
#       set_fact:
#         bind_serial: "{{ bind_current_serial.stdout | int + 1 }}"
#       when: bind_current_serial_date.stdout == current_day.stdout
#
#   when: bind_default_zone_file.stat.exists


# - name: check if serial dates are equal
#   debug:
#     msg: "{{ current_serial_date.stdout}}  equal {{ current_day.stdout }}"
#   when: current_serial_date.stdout == current_day.stdout

# - name: print current serial
#   debug:
#     msg: "{{ current_serial.stdout }}"

# - name: check if serial dates are different
#   debug:
#     msg: "{{ current_serial.stdout}} not equal {{ current_day.stdout }}"
#   when: bind_current_serial_date.stdout != current_day.stdout
