---
- name: build mkdocs site
  command: mkdocs build -f {{ mkdocs_build_config }} -d {{ mkdocs_build_output_dir }}
  become: false

- name: sync mkdocs to remote webserver
  command: rsync -a -e 'ssh -p 2849 -i /home/diogo/.ssh/id_rsa' {{ mkdocs_build_output_dir }}/ diogo@unts.xyz:/var/www/ansible.unts.xyz/
  become: false
